"""Compatibility facade for the Web application.

The HTTP server implementation lives in :mod:`stock_ai_agent.web_server`.
This module keeps the historical import path stable for the CLI, tests, and
third-party integrations while the Web layer is split into smaller modules.
"""

from .web_server import (
    ANALYSIS_START_DATE,
    BoundedThreadingHTTPServer,
    MAX_BODY_SIZE,
    PLACEHOLDER_PATTERN,
    TTLCache,
    add_dashboard_watchlist_item,
    build_dashboard_backtests_payload,
    build_dashboard_calendar_payload,
    build_dashboard_overview_payload,
    build_dashboard_payload,
    build_dashboard_performance_payload,
    build_dashboard_report_payload,
    build_dashboard_reports_payload,
    build_ready_payload,
    build_instrument_detail_payload,
    confirm_backtest_runs,
    confirm_dashboard_strategy_profile,
    confirm_dashboard_risk_config,
    remove_dashboard_watchlist_item,
    save_dashboard_strategy_profile,
    save_dashboard_risk_config,
    build_dashboard_strategies_payload,
    render_dashboard_html,
    search_watchlist_instruments,
    set_dashboard_watchlist_trading,
    serve_dashboard,
    _send,
    _send_error,
    _to_jsonable,
    _performance_range,
    _query_date,
)

__all__ = [
    "ANALYSIS_START_DATE",
    "BoundedThreadingHTTPServer",
    "MAX_BODY_SIZE",
    "PLACEHOLDER_PATTERN",
    "TTLCache",
    "add_dashboard_watchlist_item",
    "build_dashboard_backtests_payload",
    "build_dashboard_calendar_payload",
    "build_dashboard_overview_payload",
    "build_dashboard_payload",
    "build_dashboard_performance_payload",
    "build_dashboard_report_payload",
    "build_dashboard_reports_payload",
    "build_dashboard_strategies_payload",
    "build_ready_payload",
    "build_instrument_detail_payload",
    "confirm_backtest_runs",
    "confirm_dashboard_strategy_profile",
    "confirm_dashboard_risk_config",
    "remove_dashboard_watchlist_item",
    "save_dashboard_strategy_profile",
    "save_dashboard_risk_config",
    "render_dashboard_html",
    "search_watchlist_instruments",
    "set_dashboard_watchlist_trading",
    "serve_dashboard",
    "_send",
    "_send_error",
    "_to_jsonable",
    "_performance_range",
    "_query_date",
]
