from __future__ import annotations

from datetime import date
from typing import Any, List, Protocol

from ..models import Bar, Quote


class MarketDataStore(Protocol):
    def initialize(self) -> None:
        ...

    def save_bars(self, bars: List[Bar], interval: str = "daily", source: str = "unknown") -> int:
        ...

    def load_bars(self, symbol: str, interval: str = "daily", limit: int | None = None, start: date | None = None, end: date | None = None) -> List[Bar]:
        ...

    def load_bars_batch(self, symbols: list[str], interval: str = "daily", limit: int | None = None, start: date | None = None, end: date | None = None) -> dict[str, List[Bar]]:
        ...

    def ping(self) -> None:
        ...

    def last_quote_age_seconds(self) -> float | None:
        ...

    def save_quotes(self, quotes: List[Quote]) -> int:
        ...

    def load_latest_quotes(self, symbols: list[str] | None = None) -> dict[str, dict]:
        ...

    def load_quote_ticks(self, symbol: str, trade_date: date) -> list[dict]:
        ...

    def prune_market_quotes(self, trade_date: date) -> int:
        ...

    def compact_watch_decisions(self) -> int:
        ...

    def load_watchlist_items(self) -> list[dict[str, str]]:
        ...

    def add_watchlist_item(self, symbol: str, name: str, asset_type: str) -> None:
        ...

    def set_watchlist_trading_enabled(self, symbol: str, enabled: bool) -> None:
        ...

    def remove_watchlist_item(self, symbol: str) -> None:
        ...

    def has_pending_orders(self, symbol: str) -> bool:
        ...

    def load_removed_watchlist_symbols(self) -> set[str]:
        ...

    def replace_instrument_catalog(self, items: list[dict[str, str]], synced_date: str, source: str) -> int:
        ...

    def search_instrument_catalog(self, query: str, limit: int = 12) -> list[dict[str, str]]:
        ...

    def save_daily_report(self, report: dict) -> None:
        ...

    def load_daily_reports(self, limit: int = 60, offset: int = 0) -> list[dict]:
        ...

    def load_daily_report(self, report_date: date | str) -> dict | None:
        ...

    def load_trading_calendar(self, year: int, market: str = "CN") -> dict[date, bool] | None:
        ...

    def save_trading_calendar(self, year: int, trading_days: set[date], source: str, covered_until: date | None = None, market: str = "CN") -> int:
        ...

    def ensure_strategy_defaults(self, config: Any) -> None:
        ...

    def load_active_strategy_profile(self, symbol: str, asset_type: str) -> dict | None:
        ...

    def load_strategy_center(self, config: Any) -> dict:
        ...

    def save_strategy_profile(self, profile: dict, operator: str = "web") -> dict:
        ...

    def confirm_strategy_profile(self, profile_id: str, operator: str = "web") -> dict:
        ...

    def load_active_risk_config(self) -> dict | None:
        ...

    def load_risk_config_draft(self) -> dict | None:
        ...

    def save_risk_config_draft(self, payload: dict, operator: str = "web") -> dict:
        ...

    def confirm_risk_config(self, operator: str = "web") -> dict:
        ...
